<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.543">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Austin Allen">

<title>BBSA - Student Resources - BIOSTAT 718 - Homework 2</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<script src="../../../site_libs/quarto-html/quarto.js"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../../index.html">
    <span class="navbar-title">BBSA - Student Resources</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../about.html"> 
<span class="menu-text">About Austin’s MB Projects</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#question-1" id="toc-question-1" class="nav-link active" data-scroll-target="#question-1">Question 1</a>
  <ul class="collapse">
  <li><a href="#part-a" id="toc-part-a" class="nav-link" data-scroll-target="#part-a">Part a</a></li>
  <li><a href="#part-b" id="toc-part-b" class="nav-link" data-scroll-target="#part-b">Part b</a></li>
  <li><a href="#part-c" id="toc-part-c" class="nav-link" data-scroll-target="#part-c">Part c</a></li>
  <li><a href="#question-2" id="toc-question-2" class="nav-link" data-scroll-target="#question-2">Question 2</a>
  <ul class="collapse">
  <li><a href="#part-a-1" id="toc-part-a-1" class="nav-link" data-scroll-target="#part-a-1">Part a</a></li>
  <li><a href="#part-b-1" id="toc-part-b-1" class="nav-link" data-scroll-target="#part-b-1">Part b</a></li>
  <li><a href="#part-c-1" id="toc-part-c-1" class="nav-link" data-scroll-target="#part-c-1">Part c</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">BIOSTAT 718 - Homework 2</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Austin Allen </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<p>Crouse (Am J Cardiol, 2001) noted that intima-media thickness (IMT) of the carotid arteries is a generalized index of atherosclerotic disease. Previous investigators (Spence JD, Am J Cardiol 2002; Folsom AR, Stroke 1993; Howard G, Stroke 1993) have reported that IMT ranges between 0.5 to 1 mm in the general population and increases approximately 0.010 to 0.018 mm/year. Higher values of IMT are associated with more diseased arteries and cardiovascular events. These investigators and others have noted that lifestyle changes or medications may slow, arrest or induce regression in IMT. An investigation of an experimental statin – a medication for individuals at high risk of having cardiovascular disease events (e.g., myocardial infarction, stroke) – was conducted to evaluate the effect of the drug on intima-media thickness (IMT) of the carotid arteries over a one-year period. In the prospective interventional study, approximately 2000 older patients (ages between 65-95 years) were randomized equally in a blinded fashion to receive either 40 mg of an experimental statin or a placebo. Treatments were administered daily for a year.</p>
<p>The intima-media thickness (IMT) of the common carotid arteries were measured by ultrasonography and were collected at two times for the study: prior to the drug or placebo administration (Year 0), and one year later (Year 1).</p>
<p>The data are provided in an Excel file imtdata.xlsx on the class website. The study variables are:</p>
<ul>
<li>id: subject id number</li>
<li>trt: statin treatment (0=placebo, 1=40 mg experimental statin)</li>
<li>age: age of subject in years</li>
<li>imt0: IMT measurement at Year 0 (baseline)</li>
<li>imt1: IMT measurement at Year 1 (end of study)</li>
<li>imtdif: difference in one-year IMT measurements</li>
<li>male: male sex (0=female, 1=male)</li>
<li>smk: current smoking status (0=No, 1=Yes)</li>
</ul>
<p>The dataset is formatted with one record per patient. There are no missing values.</p>
<section id="question-1" class="level1">
<h1>Question 1</h1>
<p>Please investigate whether there is a treatment effect for the experimental statin by considering three models for the study endpoint (outcome):</p>
<ul>
<li>POST: Year 1 IMT outcome (IMT1)</li>
<li>CHANGE: Difference in Year 1 and Year 0 outcomes (IMT1 – IMT0)</li>
<li>ANCOVA: Year 1 IMT outcome, adjusting for Year 0 IMT outcome</li>
</ul>
<section id="part-a" class="level3">
<h3 class="anchored" data-anchor-id="part-a">Part a</h3>
<p>Fit separate models for POST, CHANGE, and ANCOVA versus the treatment indicator variable (trt: 0=placebo, 1=40 mg statin). Summarize the key estimates in a single table. Report the results in three short, separate paragraphs (one paragraph for each model). Please be sure to interpret your estimates, interval estimates, and provide p-values and your decisions.</p>
<blockquote class="blockquote">
<p>I’m going to do this a little backwards. I’m going to provide the coefficient summaries for each of the models in a combined table, then I will provide an explanation for each model in three separate sections below.</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>Coefficient Summary Table</strong></p>
</blockquote>
<div id="51381171" class="cell" data-execution_count="1">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.formula.api <span class="im">as</span> smf</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>::: {#4299a336 .cell execution_count=2} ``` {.python .cell-code} #import pandas as pd #import statsmodels.formula.api as smf</p>
<p>#Load in the data imt= pd.read_excel(“imtdata.xlsx”)</p>
<p>#———- #Question 1 #———-</p>
<p>#Part A #——</p>
<p>#Post model #Model to specify: imt1 = _0 + _1 trt + </p>
<p>#First prepare the features, noting that ‘trt’ needs to be converted to #a catgorical variable imt[“trt”]= imt[“trt”].astype(“category”)</p>
<p>#Build the post model post_model= smf.ols(“imt1 ~ trt”, data=imt).fit()</p>
<p>#Change model #Model to specify: imt1 - imt0 = _0 + _1 trt + </p>
<p>#Let’s build the features and targets for this model. Note that #the features for the post and the change are identical imt[“y_change”]= imt[“imt1”] - imt[“imt0”]</p>
<p>#Build the change model change_model= smf.ols(“y_change ~ trt”, data=imt).fit()</p>
<p>#ANCOVA model #Model to specify: imt1 = _0 + _1 trt + _2 imt0 + </p>
<p>#No new features need to be added to this model, so our existing DF is #in good shape</p>
<p>#Build the ANCOVA model ancova_model= smf.ols(“imt1 ~ trt + imt0”, data=imt).fit()</p>
<p>#Coefficient table</p>
<p>#Post post_df= pd.DataFrame(post_model.params) post_df[“std.err”]= post_model.bse post_df[“lower”]= post_df.iloc[:, 0] - 1.96 * post_df[“std.err”] post_df[“upper”]= post_df.iloc[:, 0] + 1.96 * post_df[“std.err”] post_df[“95.pct.interval”]= post_df.apply( lambda row: f”[{round(row[‘lower’], 3)}, {round(row[‘upper’], 3)}]“, axis=1 ) post_df.drop(columns=[”lower”,”upper”], inplace=True) post_df[”pvalues”]= post_model.pvalues post_df[”model”]=”Post” post_df.reset_index(inplace=True) post_df.columns= pd.Index( [ “Term”, “Estimate”, “Standard Error”, “95% Confidence”, “p-value”, “Model”, ] )</p>
<p>#Change change_df= pd.DataFrame(change_model.params) change_df[“std.err”]= change_model.bse change_df[“lower”]= change_df.iloc[:, 0] - 1.96 * change_df[“std.err”] change_df[“upper”]= change_df.iloc[:, 0] + 1.96 * change_df[“std.err”] change_df[“95.pct.interval”]= change_df.apply( lambda row: f”[{round(row[‘lower’], 3)}, {round(row[‘upper’], 3)}]“, axis=1 ) change_df.drop(columns=[”lower”,”upper”], inplace=True) change_df[”pvalues”]= change_model.pvalues change_df[”model”]=”Change” change_df.reset_index(inplace=True) change_df.columns= pd.Index( [ “Term”, “Estimate”, “Standard Error”, “95% Confidence”, “p-value”, “Model”, ] )</p>
<p>#ANCOVA ancova_df= pd.DataFrame(ancova_model.params) ancova_df[“std.err”]= ancova_model.bse ancova_df[“lower”]= ancova_df.iloc[:, 0] - 1.96 * ancova_df[“std.err”] ancova_df[“upper”]= ancova_df.iloc[:, 0] + 1.96 * ancova_df[“std.err”] ancova_df[“95.pct.interval”]= ancova_df.apply( lambda row: f”[{round(row[‘lower’], 3)}, {round(row[‘upper’], 3)}]“, axis=1 ) ancova_df.drop(columns=[”lower”,”upper”], inplace=True) ancova_df[”pvalues”]= ancova_model.pvalues ancova_df[”model”]=”ANCOVA” ancova_df.reset_index(inplace=True) ancova_df.columns= pd.Index( [ “Term”, “Estimate”, “Standard Error”, “95% Confidence”, “p-value”, “Model”, ] )</p>
<p>#Full table coefficient_table= pd.concat([post_df, change_df, ancova_df]) coefficient_table ```</p>
<p>::: {.cell-output .cell-output-display execution_count=3}</p>
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Term</th>
<th data-quarto-table-cell-role="th">Estimate</th>
<th data-quarto-table-cell-role="th">Standard Error</th>
<th data-quarto-table-cell-role="th">95% Confidence</th>
<th data-quarto-table-cell-role="th">p-value</th>
<th data-quarto-table-cell-role="th">Model</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>Intercept</td>
<td>1.050034</td>
<td>0.006953</td>
<td>[1.036, 1.064]</td>
<td>0.000000e+00</td>
<td>Post</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>trt[T.1]</td>
<td>-0.039578</td>
<td>0.009847</td>
<td>[-0.059, -0.02]</td>
<td>6.059830e-05</td>
<td>Post</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>Intercept</td>
<td>0.011539</td>
<td>0.005654</td>
<td>[0.0, 0.023]</td>
<td>4.140032e-02</td>
<td>Change</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>trt[T.1]</td>
<td>-0.032327</td>
<td>0.008008</td>
<td>[-0.048, -0.017]</td>
<td>5.627853e-05</td>
<td>Change</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>Intercept</td>
<td>0.319154</td>
<td>0.020272</td>
<td>[0.279, 0.359]</td>
<td>9.884780e-53</td>
<td>ANCOVA</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>trt[T.1]</td>
<td>-0.034474</td>
<td>0.007557</td>
<td>[-0.049, -0.02]</td>
<td>5.380897e-06</td>
<td>ANCOVA</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>imt0</td>
<td>0.703788</td>
<td>0.018833</td>
<td>[0.667, 0.741]</td>
<td>3.275665e-232</td>
<td>ANCOVA</td>
</tr>
</tbody>
</table>

</div>
<p>::: :::</p>
<blockquote class="blockquote">
<p><strong>Post Model</strong></p>
</blockquote>
<blockquote class="blockquote">
<p>The post model is the model that only considers the outcome at timepoint t=1. The formula for this model is <span class="math inline">\(Y_{i1} = \beta_0 + \beta_1X_i + \epsilon_i\)</span>. Here are the coefficient interpretations: - Intercept: The intercept is the expected (or average) IMT measurement at timepoint 1 when ‘trt’ = 0, i.e.&nbsp;it is the mean IMT measurement for the placebo group at timepoint 1. This is not particularly interesting. The value of the point estimate is 1.05 and the 95% conficence is [1.036, 1.064] (p &lt; 0.05). The p-value is not meaningful because we don’t care if the mean IMT for the placebo group is significantly different from 0 because it doesn’t make clinical sense for it to be 0. - trt: The ‘trt’ variable is the variable associated with the treatment group. The estimate -0.039 is the expected change in IMT between the treatment and control groups. Thus, we expect that on average, participants receiving statin have 0.039 units lower IMT measurements at timepoint 1 compared to participants in the control group. The 95% confidence interval is [-0.059, -0.02] (p &lt; 0.05). This indicates that the change is significantly different than 0. This is an important result.</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>Change Model</strong></p>
</blockquote>
<blockquote class="blockquote">
<p>The change model is the model that considers the outcome as the difference of timepoint 1 and timepoint 0 (i.e.&nbsp;change from baseline). The formula for this model is <span class="math inline">\((Y_{i1} Y_{i0}) = \beta_0 + \beta_1X_i + \epsilon_i\)</span>. Here are the coefficient interpretations: - Intercept: The intercept is the expected (or average) change in IMT measurement from baseline to timepoint 1 for the placebo group. This can be useful knowledge, as we may be interested to know if those in the placebo group are experiencing an increase in IMT measurements. The value of the point estimate is 0.01 and the 95% conficence is [0.0, 0.023] (p &lt; 0.05). The first thing to note is that our point estimate is in the range provided in the accompanying literature, which is what we expect for those not receiving treatment. The lower bound is not exactly zero but it is close to zero. There is a significant increase in IMT over time for those not being treated with statin. - trt: The estimate -0.032 is the expected change in IMT baseline to t1 changes between the treatment and control groups. This estimate suggests we would expect the IMT change in a person treated with statin to be 0.032 mm lower than for a person not treated with statin. The 95% confidence interval is [-0.048, -0.017] (p &lt; 0.05). This indicates that the change is significantly different than 0.</p>
<blockquote class="blockquote">
<p><strong>ANCOVA Model</strong></p>
</blockquote>
</blockquote>
<blockquote class="blockquote">
<p>The ANCOVA model is the model that considers the outcome as timepoint 1 while adjusting for timepoint 0 as a covariate. The formula for this model is <span class="math inline">\(Y_{i1} = \beta_0 + \beta_1X_i + \beta_2 Y_{i0} + \epsilon_i\)</span>. Here are the coefficient interpretations: - Intercept: The intercept is not really interpretable. It is the expected (or average) IMT measurement at timepoint 1 for the placebo group when the baseline value is 0. This is not interpretable because the baseline shouldn’t ever be equal to 0. The value of the point estimate is 0.319 and the 95% conficence is [0.279, 0.359] (p &lt; 0.05). The p-value and confidence interval are not of much interest. - trt: This coefficient is the effect of statin on IMT at timepoint 1, adjusting for baseline measrements. The estimate -0.034 is the expected change in IMT between the treatment and control groups, adjusting for baseline. Thus, we expect that on average, participants receiving statin have 0.034 units lower IMT measurements at timepoint 1 compared to participants in the control group, holding baseline constant. The 95% confidence interval is [-0.049, -0.02] (p &lt; 0.05). This indicates that the change is significantly different than 0. This is important.</p>
</blockquote>
</section>
<section id="part-b" class="level3">
<h3 class="anchored" data-anchor-id="part-b">Part b</h3>
<p>Do any of the models provide valid estimates of a treatment effect? Please explain why or why not.</p>
<blockquote class="blockquote">
<p>Yes, all three models provide valid estimates, but they reflect different aspects of the treatment effect. The post model is useful but doesn’t control for baseline differences, the change model offers a treatment effect on changes, and the ANCOVA model provides the most precise and useful estimate by controlling for baseline IMT levels. Each has its strengths, but I think the ANCOVA model is the most reliable for understanding the treatment’s effect while accounting for baseline measurements.</p>
</blockquote>
</section>
<section id="part-c" class="level3">
<h3 class="anchored" data-anchor-id="part-c">Part c</h3>
<p>For a pre-planned analysis to investigate the scientific question under the described study design, please state which model you would have used to investigate the question and justify your chosen model. (You can only choose one of the three.)</p>
<blockquote class="blockquote">
<p>As I described in part b, the ANCOVA model does a great job of providing insights into the effect of statin on IMT measurements while adjusting for baseline. We also learned in class that of the three models, the ANCOVA model provides the most precise estimates. For these reasons, ANCOVA is my choice.</p>
</blockquote>
</section>
<section id="question-2" class="level2">
<h2 class="anchored" data-anchor-id="question-2">Question 2</h2>
<p>One of the study investigators asked you, the study biostatistician, to perform analyses like the ones in Question 1. You are asked to determine whether IMT differs by sex. You are asked to fit the POST, CHANGE, and ANCOVA models noted above, but substituting in the male sex indicator variable (male: 0=female, 1=male) in place of the treatment indicator variable (trt: 0=placebo, 1=40 mg statin).</p>
<section id="part-a-1" class="level3">
<h3 class="anchored" data-anchor-id="part-a-1">Part a</h3>
<p>Fit separate models for POST, CHANGE, and ANCOVA as prescribed. Summarize the key estimates in a single table.</p>
<blockquote class="blockquote">
<p>As in question 1, I have compiled all coefficient estimates and summaries into a single table. Here it is below:</p>
</blockquote>
<div id="c36f49b7" class="cell" data-execution_count="3">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Part B</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="co"># ------</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Post model</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Model to specify: imt1 = \beta_0 + \beta_1 male + \epsilon</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="co"># First prepare the features, noting that 'male' needs to be converted to</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="co"># a catgorical variable</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>imt[<span class="st">"male"</span>] <span class="op">=</span> imt[<span class="st">"male"</span>].astype(<span class="st">"category"</span>)</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Build the post model</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>post_model <span class="op">=</span> smf.ols(<span class="st">"imt1 ~ male"</span>, data<span class="op">=</span>imt).fit()</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Change model</span></span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Model to specify: imt1 - imt0 = \beta_0 + \beta_1 male + \epsilon</span></span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Let's build the features and targets for this model. Note that</span></span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a><span class="co"># the features for the post and the change are identical</span></span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>imt[<span class="st">"y_change"</span>] <span class="op">=</span> imt[<span class="st">"imt1"</span>] <span class="op">-</span> imt[<span class="st">"imt0"</span>]</span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Build the change model</span></span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a>change_model <span class="op">=</span> smf.ols(<span class="st">"y_change ~ male"</span>, data<span class="op">=</span>imt).fit()</span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a><span class="co"># ANCOVA model</span></span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a><span class="co"># Model to specify: imt1 = \beta_0 + \beta_1 male + \beta_2 imt0 + \epsion</span></span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-28"><a href="#cb2-28" aria-hidden="true" tabindex="-1"></a><span class="co"># No new features need to be added to this model, so our existing DF is</span></span>
<span id="cb2-29"><a href="#cb2-29" aria-hidden="true" tabindex="-1"></a><span class="co"># in good shape</span></span>
<span id="cb2-30"><a href="#cb2-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-31"><a href="#cb2-31" aria-hidden="true" tabindex="-1"></a><span class="co"># Build the ANCOVA model</span></span>
<span id="cb2-32"><a href="#cb2-32" aria-hidden="true" tabindex="-1"></a>ancova_model <span class="op">=</span> smf.ols(<span class="st">"imt1 ~ male + imt0"</span>, data<span class="op">=</span>imt).fit()</span>
<span id="cb2-33"><a href="#cb2-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-34"><a href="#cb2-34" aria-hidden="true" tabindex="-1"></a><span class="co"># Coefficient table</span></span>
<span id="cb2-35"><a href="#cb2-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-36"><a href="#cb2-36" aria-hidden="true" tabindex="-1"></a><span class="co"># Post</span></span>
<span id="cb2-37"><a href="#cb2-37" aria-hidden="true" tabindex="-1"></a>post_df <span class="op">=</span> pd.DataFrame(post_model.params)</span>
<span id="cb2-38"><a href="#cb2-38" aria-hidden="true" tabindex="-1"></a>post_df[<span class="st">"std.err"</span>] <span class="op">=</span> post_model.bse</span>
<span id="cb2-39"><a href="#cb2-39" aria-hidden="true" tabindex="-1"></a>post_df[<span class="st">"lower"</span>] <span class="op">=</span> post_df.iloc[:, <span class="dv">0</span>] <span class="op">-</span> <span class="fl">1.96</span> <span class="op">*</span> post_df[<span class="st">"std.err"</span>]</span>
<span id="cb2-40"><a href="#cb2-40" aria-hidden="true" tabindex="-1"></a>post_df[<span class="st">"upper"</span>] <span class="op">=</span> post_df.iloc[:, <span class="dv">0</span>] <span class="op">+</span> <span class="fl">1.96</span> <span class="op">*</span> post_df[<span class="st">"std.err"</span>]</span>
<span id="cb2-41"><a href="#cb2-41" aria-hidden="true" tabindex="-1"></a>post_df[<span class="st">"95.pct.interval"</span>] <span class="op">=</span> post_df.<span class="bu">apply</span>(</span>
<span id="cb2-42"><a href="#cb2-42" aria-hidden="true" tabindex="-1"></a>    <span class="kw">lambda</span> row: <span class="ss">f"[</span><span class="sc">{</span><span class="bu">round</span>(row[<span class="st">'lower'</span>], <span class="dv">3</span>)<span class="sc">}</span><span class="ss">, </span><span class="sc">{</span><span class="bu">round</span>(row[<span class="st">'upper'</span>], <span class="dv">3</span>)<span class="sc">}</span><span class="ss">]"</span>, axis<span class="op">=</span><span class="dv">1</span></span>
<span id="cb2-43"><a href="#cb2-43" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb2-44"><a href="#cb2-44" aria-hidden="true" tabindex="-1"></a>post_df.drop(columns<span class="op">=</span>[<span class="st">"lower"</span>, <span class="st">"upper"</span>], inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb2-45"><a href="#cb2-45" aria-hidden="true" tabindex="-1"></a>post_df[<span class="st">"pvalues"</span>] <span class="op">=</span> post_model.pvalues</span>
<span id="cb2-46"><a href="#cb2-46" aria-hidden="true" tabindex="-1"></a>post_df[<span class="st">"model"</span>] <span class="op">=</span> <span class="st">"Post"</span></span>
<span id="cb2-47"><a href="#cb2-47" aria-hidden="true" tabindex="-1"></a>post_df.reset_index(inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb2-48"><a href="#cb2-48" aria-hidden="true" tabindex="-1"></a>post_df.columns <span class="op">=</span> pd.Index(</span>
<span id="cb2-49"><a href="#cb2-49" aria-hidden="true" tabindex="-1"></a>    [</span>
<span id="cb2-50"><a href="#cb2-50" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Term"</span>,</span>
<span id="cb2-51"><a href="#cb2-51" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Estimate"</span>,</span>
<span id="cb2-52"><a href="#cb2-52" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Standard Error"</span>,</span>
<span id="cb2-53"><a href="#cb2-53" aria-hidden="true" tabindex="-1"></a>        <span class="st">"95% Confidence"</span>,</span>
<span id="cb2-54"><a href="#cb2-54" aria-hidden="true" tabindex="-1"></a>        <span class="st">"p-value"</span>,</span>
<span id="cb2-55"><a href="#cb2-55" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Model"</span>,</span>
<span id="cb2-56"><a href="#cb2-56" aria-hidden="true" tabindex="-1"></a>    ]</span>
<span id="cb2-57"><a href="#cb2-57" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb2-58"><a href="#cb2-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-59"><a href="#cb2-59" aria-hidden="true" tabindex="-1"></a><span class="co"># Change</span></span>
<span id="cb2-60"><a href="#cb2-60" aria-hidden="true" tabindex="-1"></a>change_df <span class="op">=</span> pd.DataFrame(change_model.params)</span>
<span id="cb2-61"><a href="#cb2-61" aria-hidden="true" tabindex="-1"></a>change_df[<span class="st">"std.err"</span>] <span class="op">=</span> change_model.bse</span>
<span id="cb2-62"><a href="#cb2-62" aria-hidden="true" tabindex="-1"></a>change_df[<span class="st">"lower"</span>] <span class="op">=</span> change_df.iloc[:, <span class="dv">0</span>] <span class="op">-</span> <span class="fl">1.96</span> <span class="op">*</span> change_df[<span class="st">"std.err"</span>]</span>
<span id="cb2-63"><a href="#cb2-63" aria-hidden="true" tabindex="-1"></a>change_df[<span class="st">"upper"</span>] <span class="op">=</span> change_df.iloc[:, <span class="dv">0</span>] <span class="op">+</span> <span class="fl">1.96</span> <span class="op">*</span> change_df[<span class="st">"std.err"</span>]</span>
<span id="cb2-64"><a href="#cb2-64" aria-hidden="true" tabindex="-1"></a>change_df[<span class="st">"95.pct.interval"</span>] <span class="op">=</span> change_df.<span class="bu">apply</span>(</span>
<span id="cb2-65"><a href="#cb2-65" aria-hidden="true" tabindex="-1"></a>    <span class="kw">lambda</span> row: <span class="ss">f"[</span><span class="sc">{</span><span class="bu">round</span>(row[<span class="st">'lower'</span>], <span class="dv">3</span>)<span class="sc">}</span><span class="ss">, </span><span class="sc">{</span><span class="bu">round</span>(row[<span class="st">'upper'</span>], <span class="dv">3</span>)<span class="sc">}</span><span class="ss">]"</span>, axis<span class="op">=</span><span class="dv">1</span></span>
<span id="cb2-66"><a href="#cb2-66" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb2-67"><a href="#cb2-67" aria-hidden="true" tabindex="-1"></a>change_df.drop(columns<span class="op">=</span>[<span class="st">"lower"</span>, <span class="st">"upper"</span>], inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb2-68"><a href="#cb2-68" aria-hidden="true" tabindex="-1"></a>change_df[<span class="st">"pvalues"</span>] <span class="op">=</span> change_model.pvalues</span>
<span id="cb2-69"><a href="#cb2-69" aria-hidden="true" tabindex="-1"></a>change_df[<span class="st">"model"</span>] <span class="op">=</span> <span class="st">"Change"</span></span>
<span id="cb2-70"><a href="#cb2-70" aria-hidden="true" tabindex="-1"></a>change_df.reset_index(inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb2-71"><a href="#cb2-71" aria-hidden="true" tabindex="-1"></a>change_df.columns <span class="op">=</span> pd.Index(</span>
<span id="cb2-72"><a href="#cb2-72" aria-hidden="true" tabindex="-1"></a>    [</span>
<span id="cb2-73"><a href="#cb2-73" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Term"</span>,</span>
<span id="cb2-74"><a href="#cb2-74" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Estimate"</span>,</span>
<span id="cb2-75"><a href="#cb2-75" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Standard Error"</span>,</span>
<span id="cb2-76"><a href="#cb2-76" aria-hidden="true" tabindex="-1"></a>        <span class="st">"95% Confidence"</span>,</span>
<span id="cb2-77"><a href="#cb2-77" aria-hidden="true" tabindex="-1"></a>        <span class="st">"p-value"</span>,</span>
<span id="cb2-78"><a href="#cb2-78" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Model"</span>,</span>
<span id="cb2-79"><a href="#cb2-79" aria-hidden="true" tabindex="-1"></a>    ]</span>
<span id="cb2-80"><a href="#cb2-80" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb2-81"><a href="#cb2-81" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-82"><a href="#cb2-82" aria-hidden="true" tabindex="-1"></a><span class="co"># ANCOVA</span></span>
<span id="cb2-83"><a href="#cb2-83" aria-hidden="true" tabindex="-1"></a>ancova_df <span class="op">=</span> pd.DataFrame(ancova_model.params)</span>
<span id="cb2-84"><a href="#cb2-84" aria-hidden="true" tabindex="-1"></a>ancova_df[<span class="st">"std.err"</span>] <span class="op">=</span> ancova_model.bse</span>
<span id="cb2-85"><a href="#cb2-85" aria-hidden="true" tabindex="-1"></a>ancova_df[<span class="st">"lower"</span>] <span class="op">=</span> ancova_df.iloc[:, <span class="dv">0</span>] <span class="op">-</span> <span class="fl">1.96</span> <span class="op">*</span> ancova_df[<span class="st">"std.err"</span>]</span>
<span id="cb2-86"><a href="#cb2-86" aria-hidden="true" tabindex="-1"></a>ancova_df[<span class="st">"upper"</span>] <span class="op">=</span> ancova_df.iloc[:, <span class="dv">0</span>] <span class="op">+</span> <span class="fl">1.96</span> <span class="op">*</span> ancova_df[<span class="st">"std.err"</span>]</span>
<span id="cb2-87"><a href="#cb2-87" aria-hidden="true" tabindex="-1"></a>ancova_df[<span class="st">"95.pct.interval"</span>] <span class="op">=</span> ancova_df.<span class="bu">apply</span>(</span>
<span id="cb2-88"><a href="#cb2-88" aria-hidden="true" tabindex="-1"></a>    <span class="kw">lambda</span> row: <span class="ss">f"[</span><span class="sc">{</span><span class="bu">round</span>(row[<span class="st">'lower'</span>], <span class="dv">3</span>)<span class="sc">}</span><span class="ss">, </span><span class="sc">{</span><span class="bu">round</span>(row[<span class="st">'upper'</span>], <span class="dv">3</span>)<span class="sc">}</span><span class="ss">]"</span>, axis<span class="op">=</span><span class="dv">1</span></span>
<span id="cb2-89"><a href="#cb2-89" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb2-90"><a href="#cb2-90" aria-hidden="true" tabindex="-1"></a>ancova_df.drop(columns<span class="op">=</span>[<span class="st">"lower"</span>, <span class="st">"upper"</span>], inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb2-91"><a href="#cb2-91" aria-hidden="true" tabindex="-1"></a>ancova_df[<span class="st">"pvalues"</span>] <span class="op">=</span> ancova_model.pvalues</span>
<span id="cb2-92"><a href="#cb2-92" aria-hidden="true" tabindex="-1"></a>ancova_df[<span class="st">"model"</span>] <span class="op">=</span> <span class="st">"ANCOVA"</span></span>
<span id="cb2-93"><a href="#cb2-93" aria-hidden="true" tabindex="-1"></a>ancova_df.reset_index(inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb2-94"><a href="#cb2-94" aria-hidden="true" tabindex="-1"></a>ancova_df.columns <span class="op">=</span> pd.Index(</span>
<span id="cb2-95"><a href="#cb2-95" aria-hidden="true" tabindex="-1"></a>    [</span>
<span id="cb2-96"><a href="#cb2-96" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Term"</span>,</span>
<span id="cb2-97"><a href="#cb2-97" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Estimate"</span>,</span>
<span id="cb2-98"><a href="#cb2-98" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Standard Error"</span>,</span>
<span id="cb2-99"><a href="#cb2-99" aria-hidden="true" tabindex="-1"></a>        <span class="st">"95% Confidence"</span>,</span>
<span id="cb2-100"><a href="#cb2-100" aria-hidden="true" tabindex="-1"></a>        <span class="st">"p-value"</span>,</span>
<span id="cb2-101"><a href="#cb2-101" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Model"</span>,</span>
<span id="cb2-102"><a href="#cb2-102" aria-hidden="true" tabindex="-1"></a>    ]</span>
<span id="cb2-103"><a href="#cb2-103" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb2-104"><a href="#cb2-104" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-105"><a href="#cb2-105" aria-hidden="true" tabindex="-1"></a><span class="co"># Full table</span></span>
<span id="cb2-106"><a href="#cb2-106" aria-hidden="true" tabindex="-1"></a>coefficient_table <span class="op">=</span> pd.concat([post_df, change_df, ancova_df])</span>
<span id="cb2-107"><a href="#cb2-107" aria-hidden="true" tabindex="-1"></a>coefficient_table</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="4">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Term</th>
<th data-quarto-table-cell-role="th">Estimate</th>
<th data-quarto-table-cell-role="th">Standard Error</th>
<th data-quarto-table-cell-role="th">95% Confidence</th>
<th data-quarto-table-cell-role="th">p-value</th>
<th data-quarto-table-cell-role="th">Model</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>Intercept</td>
<td>0.992568</td>
<td>0.006253</td>
<td>[0.98, 1.005]</td>
<td>0.000000e+00</td>
<td>Post</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>male[T.1]</td>
<td>0.093873</td>
<td>0.009862</td>
<td>[0.075, 0.113]</td>
<td>4.844360e-21</td>
<td>Post</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>Intercept</td>
<td>-0.009314</td>
<td>0.005196</td>
<td>[-0.019, 0.001]</td>
<td>7.323624e-02</td>
<td>Change</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>male[T.1]</td>
<td>0.011786</td>
<td>0.008196</td>
<td>[-0.004, 0.028]</td>
<td>1.505678e-01</td>
<td>Change</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>Intercept</td>
<td>0.304309</td>
<td>0.019857</td>
<td>[0.265, 0.343]</td>
<td>3.343071e-50</td>
<td>ANCOVA</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>male[T.1]</td>
<td>0.037482</td>
<td>0.007862</td>
<td>[0.022, 0.053]</td>
<td>1.997855e-06</td>
<td>ANCOVA</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>imt0</td>
<td>0.686967</td>
<td>0.019211</td>
<td>[0.649, 0.725]</td>
<td>7.172503e-217</td>
<td>ANCOVA</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</section>
<section id="part-b-1" class="level3">
<h3 class="anchored" data-anchor-id="part-b-1">Part b</h3>
<p>Interpret the estimated regression coefficient for the male sex variable for each of the three models fitted in part (a). Are the estimates approximately the same in magnitude? Are the interpretations the same for the three models? Please explain why or why not.</p>
<blockquote class="blockquote">
<p>The format for this response will be similar to Question 1, part a, but I will focus solely on the ‘male’ coefficient.</p>
<p><strong>Post Model</strong></p>
<ul>
<li>Interpretation: The point estimate is 0.093, with a 95% confidence interval of [0.075, 0.113] (p &lt; 0.05). This suggests that on average, men have a timepoint 1 reading of IMT that is 0.093 mm higher than women. This result is significant.</li>
</ul>
<p><strong>Change Model</strong></p>
<ul>
<li>Interpretation: A point estimate of 0.011 suggests that men, on average, see a higher change in IMT readings from baseline to timepoint 1. However, this result is not significant. The 95% confidence interval is [-0.004, 0.028] (p-value &gt; 0.05). This indicates that the effect of sex on the change in IMT from baseline to timepoint 1 is not significant.</li>
</ul>
<p><strong>ANCOVA Model</strong></p>
<ul>
<li>Interpretation: The point estimate of 0.037 suggests that men have an average IMT at timepoint 1 that is 0.037 higher than the average for women, adjusting for baseline values of IMT. The 955 confidence interval is [0.022, 0.053] (p-value &lt; 0.05) indicating a significant result.</li>
</ul>
<p>Next, I will discuss the posed questions:</p>
<ul>
<li>“Are the estimates approximately the same in magnitude?” Not really. The values are relatively close, but the estimate for the post model is roughly 9 times higher than that of the change model (the ANCOVA model estimate is somewhere in the middle). This is likely due to what we discussed in Question 1 part b. These estimates are different ways of looking at how sex affects IMT, so we can’t expect them to be the same.</li>
<li>“Are the interpretations the same for the three models? Why or why not?” Again, the interpretations are <strong>not</strong> the same, and this is for the reason described in the last bullet point. These three models look at the effect of sex on IMT in different ways, so we interpret them differently.</li>
</ul>
</blockquote>
</section>
<section id="part-c-1" class="level3">
<h3 class="anchored" data-anchor-id="part-c-1">Part c</h3>
<p>If the study investigator who asked you to perform the analyses mentioned their objective was to learn if IMT differs over time by sex, would the three models be acceptable to address the investigator’s objective? If not, which model or models would be most appropriate? Briefly explain.</p>
<blockquote class="blockquote">
<p>No, not all three models are equipped to answer this question. I believe that the change model is the most appropriate to answer this question because it’s looking at a change over time by sex. We would need to do some fancy maneuvering to get the ANCOVA model into ship-shape (probably including interaction terms etc.), and the post-model doesn’t even consider time. So I’m going to say that the change model is the most appropriate for this scenario.</p>
</blockquote>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>